name: 'Swift Playgrounds'
description: 'Run all Swift Playgrounds in the repo'
author: 'Henrik Storch <@thisisthefoxe>'

branding:
  color: 'orange'
  icon: 'play'

runs:
  using: "composite"
  
  steps:
    - id: run-swift-files
      run: ${{ github.action_path }}/pg.sh
      shell: bash
