name: Playgrounds CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: thisisthefoxe/swift-playgrounds-action@master
